package processor

import (
	"context"
	"fmt"
	"log/slog"
	"strconv"

	"pr-review-automation/internal/config"
	"pr-review-automation/internal/domain"
	"pr-review-automation/internal/metrics"

	"golang.org/x/sync/errgroup"
)

func (p *PRProcessor) postComments(ctx context.Context, pr *domain.PullRequest, review *domain.ReviewResult, existingComments []domain.ReviewComment) error {
	if p.cfg.Pipeline.CommentMerge.Enabled {
		return p.postMergedComments(ctx, pr, review, existingComments)
	}
	return p.postIndividualComments(ctx, pr, review.Comments)
}

func (p *PRProcessor) postMergedComments(ctx context.Context, pr *domain.PullRequest, review *domain.ReviewResult, existingComments []domain.ReviewComment) error {
	merger := NewCommentMerger(&p.cfg.Pipeline.CommentMerge)
	result := merger.Merge(review.Comments, pr.LatestCommit)

	pullRequestId, _ := strconv.Atoi(pr.ID)

	// 1. Post file-level comments
	// Filter existing file comments
	toPostFiles := p.filterExistingFileComments(existingComments, result.FileComments, pr.LatestCommit)

	for _, fc := range toPostFiles {
		fc.ModelName = review.Model
		commentText := merger.FormatFileComment(&fc)

		args := map[string]interface{}{
			"projectKey":    pr.ProjectKey,
			"repoSlug":      pr.RepoSlug,
			"pullRequestId": pullRequestId,
			"commentText":   commentText,
		}
		// File comments are general comments on the PR, but maybe we can attach to file level?
		// Bitbucket API supports file path for general file comments usually?
		// bitbucket_add_pull_request_comment can take 'filePath'.
		// If we provide filePath but no line, it's a file comment.
		if fc.FilePath != "" {
			args["filePath"] = fc.FilePath
		}

		slog.Debug("post merged file comment", "file", fc.FilePath)
		_, err := p.commenter.CallTool(ctx, config.MCPServerBitbucket, config.ToolBitbucketAddComment, args)
		if err != nil {
			slog.Error("post merged comment failed", "file", fc.FilePath, "error", err)
			metrics.CommentPostFailures.WithLabelValues("api_error").Inc()
		}
	}

	// 1b. Post individual (NotMerged) high-severity comments (Hybrid Mode)
	// Filter those first
	toPostIndividual := p.filterDuplicates(result.NotMerged, existingComments)
	if len(toPostIndividual) > 0 {
		slog.Debug("post hybrid individual comments", "count", len(toPostIndividual))
		if err := p.postIndividualComments(ctx, pr, toPostIndividual); err != nil {
			slog.Error("post hybrid individual comments failed", "error", err)
		}
	}

	// 2. Post summary with INFO/NIT appended
	// Check if summary for this commit already exists
	if !p.hasExistingSummary(existingComments, pr.LatestCommit) {
		summaryText := review.Summary
		addonsText := merger.FormatSummaryAddons(result.SummaryAddons)

		fullSummary := fmt.Sprintf("**AI Review Summary (Model: %s)**\nScore: %d\n\n%s%s",
			review.Model, review.Score, summaryText, addonsText)

		// Add marker
		marker := fmt.Sprintf("%s%s:%s%s", config.MarkerAIReviewPrefix, config.MarkerTypeSummary, pr.LatestCommit, config.MarkerAIReviewSuffix)
		footer := fmt.Sprintf("\n---\n*Automatically generated by %s*", review.Model)
		fullSummary = marker + "\n\n" + fullSummary + footer

		args := map[string]interface{}{
			"projectKey":    pr.ProjectKey,
			"repoSlug":      pr.RepoSlug,
			"pullRequestId": pullRequestId,
			"commentText":   fullSummary,
		}

		_, err := p.commenter.CallTool(ctx, config.MCPServerBitbucket, config.ToolBitbucketAddComment, args)
		if err != nil {
			slog.Error("post summary failed", "error", err)
			metrics.CommentPostFailures.WithLabelValues("summary_error").Inc()
		}
	} else {
		slog.Info("summary for commit already exists, skipping", "commit", pr.LatestCommit)
	}

	return p.cleanupSession(pr.ID)
}

func (p *PRProcessor) postIndividualComments(ctx context.Context, pr *domain.PullRequest, comments []domain.ReviewComment) error {
	pullRequestId, err := strconv.Atoi(pr.ID)
	if err != nil {
		return fmt.Errorf("invalid pr id: %s", pr.ID)
	}

	// Use errgroup to post comments in parallel
	limit := p.cfg.Pipeline.MaxConcurrentComments
	if limit <= 0 {
		limit = 5
	}
	g, gCtx := errgroup.WithContext(ctx)
	g.SetLimit(limit)

	for _, comment := range comments {
		comment := comment
		g.Go(func() error {
			args := map[string]interface{}{
				"projectKey":    pr.ProjectKey,
				"repoSlug":      pr.RepoSlug,
				"pullRequestId": pullRequestId,
				"commentText":   fmt.Sprintf("%s%s:%d:%s%s\n%s", config.MarkerAIReviewPrefix, comment.File, comment.Line, pr.LatestCommit, config.MarkerAIReviewSuffix, comment.Comment),
			}

			if comment.File != "" {
				args["filePath"] = comment.File
				if comment.Line > 0 {
					args["lineNumber"] = comment.Line
				}
			}

			slog.Debug("post comment", "file", comment.File, "line", comment.Line)
			_, err := p.commenter.CallTool(gCtx, config.MCPServerBitbucket, config.ToolBitbucketAddComment, args)
			if err != nil {
				slog.Error("post comment failed", "file", comment.File, "error", err)
				metrics.CommentPostFailures.WithLabelValues("api_error").Inc()
				return nil
			}
			return nil
		})
	}

	if err := g.Wait(); err != nil {
		slog.Warn("some comments failed to post", "error", err)
	}
	return p.cleanupSession(pr.ID)
}

func (p *PRProcessor) cleanupSession(prID string) error {
	if cleaner, ok := p.commenter.(interface{ ClearSessionHistory(string) }); ok {
		cleaner.ClearSessionHistory("pr-" + prID)
	}
	return nil
}
